apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc-azurefile 
  namespace: hpcc-systems
spec:
  releaseName: hpcc-azurefile
  chart:
    spec:
      chart: helm/examples/azure/hpcc-azurefile
      sourceRef:
        kind: GitRepository
        name: hpcc-chart-git
        namespace: flux-system
      valuesFiles:
        - helm/examples/azure/hpcc-azurefile/values.yaml
  interval: 5m
  install:
    remediation:
      retries: 3
# values:
