apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc
  namespace: hpcc-systems
spec:
  chart:
    spec:
      version: ">=8.2.0"
      valuesFiles:
        - helm/hpcc/values.yaml
        - helm/examples/local/values-localfile.yaml
  test:
    enable: true

  values:
    global:
      image:
        version: 8.2.0-2
