apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hpcc-systems
resources:
  - ../../base/hpcc
  - ../../base/local
  - ../../base/elastic
patches:
  - path: storage-values.yaml
  - path: hpcc-values.yaml
