apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/hpcc
  - ../../base/local
  - ../../base/elastic
patches:
  - path: hpcc-values.yaml
#  - path: esp-services.yaml
