apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hpcc-systems
resources:
  - ../../base/namespaces
  - ../../base/hpcc
  - ../../base/local
  - ../../base/elastic
patchesStrategicMerge:
  - hpcc-values.yaml
