---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: localfile2
  secretRef:
    name: flux-system
  url: https://github.com/xwang2713/flux2-hpcc-cluster.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/azure/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
