apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc
spec:
  releaseName: hpcc
  chart:
    spec:
      chart: helm/hpcc
      sourceRef:
        kind: GitRepository
        name: hpcc-chart-git
        namespace: flux-system
  interval: 2m
  install:
    remediation:
      retries: 3
