apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localfile 
  namespace: hpcc-systems
spec:
  releaseName: localfile
  chart:
    spec:
      chart: helm/examples/local/hpcc-localfile
      sourceRef:
        kind: GitRepository
        name: hpcc-chart
        namespace: flux-system
      valuesFiles:
        - helm/examples/local/hpcc-localfile/values.yaml
  interval: 5m
  install:
    remediation:
      retries: 3
  Values:
    common:
      hostpath: "/c/hpcc-data"
