apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch 
  namespace: hpcc-systems
spec:
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: "7.9.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    extraInitContainers:
      - name: data-dir
        image: busybox:1.28
        command: [ '/bin/sh', '-c', 'mkdir -p /usr/share/elasticsearch/data && chown -R 1000:1000 /usr/share/elasticsearch/ ' ]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-master
    replicas: 1
    minimumMasterNodes: 1
