apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc-localfile 
spec:
  releaseName: hpcc-localfile
  chart:
    spec:
      chart: helm/examples/local/hpcc-localfile
      sourceRef:
        kind: GitRepository
        name: hpcc-chart-git
        namespace: flux-system
   interval: 5m
   install:
     remediation:
       retries: 3
