apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc-localfile 
  namespace: hpcc-systems
spec:
  releaseName: hpcc-localfile
  chart:
    spec:
      chart: helm/examples/local/hpcc-localfile
      sourceRef:
        kind: GitRepository
        name: hpcc-chart-git
        namespace: flux-system
      version: "1.6.0"
      valuesFiles:
        - helm/examples/local/hpcc-localfile/values.yaml
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    common:
      hostpath: "/c/hpcc-data"
