elasticsearch:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value:  "spot"
      effect: "NoSchedule"

filebeat:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value:  "spot"
      effect: "NoSchedule"
    - key: "HPCCCriticalOnly"
      operator: "Equal"
      value:  "true"
      effect: "NoSchedule"
    - key: "HPCCThorOnly"
      operator: "Equal"
      value:  "true"
      effect: "NoSchedule"
kibana:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value:  "spot"
      effect: "NoSchedule"
