apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc
  namespace: hpcc-systems
spec:
  chart:
    spec:
      version: "8.2.x"
      valuesFiles:
        - helm/hpcc/values.yaml
        - helm/examples/azure/values-retained-azurefile.yaml
  test:
    enable: true
  values:
    global:
      image:
        version: 8.2.6
    placements:
      - pods: ["all"]
        placement:
          tolerations:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"
      - pods: ["type:dali","type:sasha"]
        placement:
          tolerations:
            - key: "HPCCCriticalOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
      - pods: ["type:thor"]
        placement:
          tolerations:
            - key: "HPCCThorOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: v1
            kind: Service
            metadata: 
              name: "eclwatch"
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "false"
