apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/azure
  - ../../base/hpcc
  - ../../base/config
  - ../../base/elastic

patchesStrategicMerge:
  - storage-values.yaml
  - hpcc-values.yaml
  - ../../base/elastic/elastic-values.yaml
