apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc
  namespace: hpcc-systems
spec:
  chart:
    spec:
      version: ">=8.0.20"
  test:
    enable: test

  values:
    global:
      image:
        version: 8.0.20-1
