apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk
spec:
  releaseName: elk
  chart:
    spec:
      chart: elastic4hpcclogs
      sourceRef:
        kind: HelmRepository
        name: hpcc-chart-helm
        namespace: flux-system
  interval: 10m0s
#  install:
#    remediation:
#      retries: 1
