apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch 
  namespace: hpcc-systems
spec:
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: "7.9.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    replicas: 1
      minimumMasterNodes: 1
