apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: hpcc-systems
spec:
  releaseName: kibana
  chart:
    spec:
      chart: kibana
      sourceRef:
        kind: GitRepository
        name: elastic
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
