apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hpcc
  namespace: hpcc-systems
spec:
  chart:
    spec:
      version: "8.2.x"
      valuesFiles:
    #
    #stRenderer specification.
        - helm/hpcc/values.yaml
        - helm/examples/azure/values-retained-azurefile.yaml
  test:
    enable: true
  values:
    global:
      image:
        version: 8.2.0-2
    #esp:
    #  name: eclwatch
    #  application: eclwatch 
    #   auth: none
    #   replicas: 1
    #   service:
    #     port: 8888     
    #     servicePort: 8010
    #     visibility: global
  postRenderers:
    - kustomiz:
        patchesStrategicMerge:
          - esp-service.yaml
