apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hpcc-systems
resources:
  - ../../base/azure/storage.yaml
  - ../../base/hpcc
  - ../../base/elastic
patchesStrategicMerge:
  - storage-values.yaml
  - hpcc-values.yaml
