apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/azure
  - ../../base/hpcc
  - ../../base/elastic
patchesStrategicMerge:
  - storage-values.yaml
  - hpcc-values.yaml
patches:
  - target:
      kind: Service
      name: eclwatch
    path: esp-services.yaml
