apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/azure/storage.yaml
  - ../../base/hpcc
  - ../../base/elastic
patchesStrategicMerge:
  - storage-values.yaml
  - hpcc-values.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Service
      name: hpcc-systems
    path: esp-services.yaml
